# version: '3.8'

# services:
#   mysqldb:
#     container_name: mysql
#     image: mysql
#     restart: always
#     environment: 
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USERNAME: root
#       MYSQL_DATABASE: test
#     ports:
#       - 3306:3306
#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq
#     restart: always
#     ports:
#       - 15672:15672
#       - 5672:5672    
#   authentication-service:
#     depends_on:
#       - mysqldb
#     build: ./
#     restart: unless-stopped
#     ports:
#       - 4000:4000
#     environment:
#       - DB_HOST=mysqldb
#       - DB_USER=root
#       - DB_PASSWORD=root
#       - DB_NAME=test
#       - DB_PORT=3306:3306
#     stdin_open: true
#     tty: true
#   api-gateway-service:
#     build: ./
#     restart: unless-stopped
#     ports:
#       - 8080:8080
#     stdin_open: true
#     tty: true  

# volumes: 
#   db: